# Generated by Django 6.0.3 on 2026-03-12 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coursemodule_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.IntegerField(help_text='0 for A, 1 for B, 2 for C, 3 for D')),
                ('domain', models.CharField(choices=[('web', 'Web Development'), ('ds', 'Data Science'), ('ai', 'AI/ML'), ('devops', 'DevOps'), ('dsa', 'DSA & Algorithms')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='api.skill')),
            ],
        ),
    ]
