# Generated by Django 6.0.3 on 2026-05-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assessmentquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='provider',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
