# Generated by Django 6.0.3 on 2026-05-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_external_url_course_is_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
