# Generated by Django 6.0.3 on 2026-05-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_what_you_will_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='external_url',
            field=models.URLField(blank=True),
        ),
    ]
