# Generated by Django 6.0.3 on 2026-05-02 01:40

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dailystudytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystudytime',
            name='date',
            field=models.DateField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
