'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Upload, FileText, CheckCircle, Zap, Target, TrendingUp, ChevronRight, User, Code2, Briefcase, Brain } from 'lucide-react';
import DashboardLayout from '../dashboard/layout';
import { apiFetch } from '../../lib/api';
import { jsPDF } from 'jspdf';

export default function ResumePage() {
  const [stage, setStage] = useState<'upload' | 'analyzing' | 'result'>('upload');
  const [dragging, setDragging] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  const [analysis, setAnalysis] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault(); setDragging(false);
    if (e.dataTransfer.files[0]) { setFile(e.dataTransfer.files[0]); }
  };
  const handleFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) { setFile(e.target.files[0]); }
  };
  
  const handleAnalyze = async () => {
    if (!file) return;
    setStage('analyzing');
    
    const formData = new FormData();
    formData.append('file', file);

    try {
        const token = localStorage.getItem('access');
        const response = await fetch('${process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000"}/api/resume/upload/', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${token}`
            },
            body: formData
        });
        
        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            throw new Error(errorData.error || 'Server error');
        }

        const result = await response.json();
        if (result.data && result.data.analysis_result) {
            setAnalysis(result.data.analysis_result);
            setStage('result');
        } else {
            throw new Error('Invalid response format');
        }
    } catch (err) {
        console.error('Analysis failed:', err);
        alert('Failed to analyze resume. Please try again.');
        setStage('upload');
    }
  };

  const handleDownloadReport = () => {
    if (!analysis) return;
    
    const doc = new jsPDF();
    const margin = 20;
    let y = 30;

    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(99, 102, 241); // Primary color
    doc.text('SmartLearn Analysis Report', margin, y);
    y += 15;

    // Profile Details
    doc.setFontSize(16);
    doc.setTextColor(31, 41, 55);
    doc.text('Candidate Profile', margin, y);
    y += 10;
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(75, 85, 99);
    doc.text(`Name: ${analysis.name}`, margin, y);
    y += 7;
    doc.text(`Level: ${analysis.seniority_level}`, margin, y);
    y += 7;
    doc.text(`Experience: ${analysis.experience_years} Years`, margin, y);
    y += 7;
    doc.text(`Resume Score: ${analysis.resume_score}/100`, margin, y);
    y += 15;

    // Skills
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(31, 41, 55);
    doc.text('Extracted Skills', margin, y);
    y += 10;
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    const skills = analysis.extracted_skills.join(', ');
    const splitSkills = doc.splitTextToSize(skills, 170);
    doc.text(splitSkills, margin, y);
    y += (splitSkills.length * 7) + 10;

    // Skill Gaps
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('Identified Gaps', margin, y);
    y += 10;
    
    doc.setFont('helvetica', 'normal');
    analysis.skill_gaps.forEach((gap: string) => {
        doc.text(`• ${gap}`, margin, y);
        y += 7;
    });
    y += 10;

    // Recommendations
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('AI Recommendations', margin, y);
    y += 10;
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    analysis.suggestions.forEach((tip: string) => {
        const splitTip = doc.splitTextToSize(`• ${tip}`, 170);
        doc.text(splitTip, margin, y);
        y += (splitTip.length * 6);
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(156, 163, 175);
    doc.text(`Generated by SmartLearn AI on ${new Date().toLocaleDateString()}`, margin, 280);

    doc.save(`Analysis_Report_${analysis.name.replace(/\s+/g, '_')}.pdf`);
  };

  const handleGeneratePath = async (specificSkill?: string) => {
    setLoading(true);
    try {
      const res = await apiFetch('/learning-path/', {
        method: 'POST',
        body: JSON.stringify({
          goal: specificSkill ? `Master ${specificSkill}` : (analysis?.seniority_level + " " + (analysis?.skill_gaps?.[0] || "Developer"))
        })
      });
      if (res.data) {
        router.push('/learning-path');
      }
    } catch (err) {
      alert('Failed to generate path');
    } finally {
      setLoading(false);
    }
  };

  const handleLearnClick = (gap: string) => {
    router.push(`/courses?search=${encodeURIComponent(gap)}&recommend=true`);
  };

  return (
    <DashboardLayout>
      <div>
        <div style={{ marginBottom: '2rem' }}>
          <h1 style={{ fontFamily: 'Outfit,sans-serif', fontSize: '1.75rem', fontWeight: 800, color: '#f1f5f9' }}>Resume Analysis</h1>
          <p style={{ color: 'var(--text-muted)', marginTop: '0.25rem' }}>Upload your resume for AI-powered skill extraction and gap analysis.</p>
        </div>

        {stage === 'upload' && (
          <div style={{ maxWidth: 600, margin: '0 auto' }}>
            <div onDragOver={e => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={handleDrop}
              style={{ padding: '3rem', border: `2px dashed ${dragging ? 'var(--primary)' : 'var(--border)'}`, borderRadius: '1.5rem', textAlign: 'center', background: dragging ? 'rgba(99,102,241,0.08)' : 'rgba(255,255,255,0.02)', cursor: 'pointer', transition: 'all 0.3s', marginBottom: '1.5rem' }}>
              <Upload size={48} color={dragging ? '#818cf8' : 'var(--text-muted)'} style={{ margin: '0 auto 1rem', display: 'block' }} />
              <h3 style={{ fontWeight: 700, color: '#f1f5f9', marginBottom: '0.5rem' }}>Drop your resume here</h3>
              <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '1.25rem' }}>Supports PDF, DOCX, DOC (max 10MB)</p>
              <label htmlFor="resume-input" className="btn-primary" style={{ cursor: 'pointer' }}>
                <FileText size={16} /> Browse Files
              </label>
              <input id="resume-input" type="file" accept=".pdf,.doc,.docx,.txt" style={{ display: 'none' }} onChange={handleFile} />
              {file && <p style={{ marginTop: '1rem', color: '#34d399', fontSize: '0.85rem', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.4rem' }}><CheckCircle size={14} /> {file.name}</p>}
            </div>
            <button id="analyze-resume-btn" className="btn-primary" style={{ width: '100%', justifyContent: 'center', padding: '0.9rem', opacity: file ? 1 : 0.5 }} onClick={handleAnalyze} disabled={!file}>
              <Zap size={16} /> Analyse with AI <ChevronRight size={16} />
            </button>
          </div>
        )}

        {stage === 'analyzing' && (
          <div style={{ textAlign: 'center', padding: '4rem', maxWidth: 400, margin: '0 auto' }}>
            <div style={{ width: 80, height: 80, borderRadius: '50%', background: 'rgba(99,102,241,0.15)', border: '3px solid rgba(99,102,241,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1.5rem', animation: 'pulse-glow 2s infinite' }}>
              <Brain size={36} color="#818cf8" />
            </div>
            <h2 style={{ fontFamily: 'Outfit,sans-serif', fontWeight: 800, color: '#f1f5f9', marginBottom: '0.5rem' }}>Analysing Resume...</h2>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '2rem' }}>AI is extracting skills, experience, and identifying gaps</p>
            {['Parsing document structure...', 'Extracting skills & technologies...', 'Identifying skill gaps...', 'Generating recommendations...'].map((step, i) => (
              <div key={step} style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem', opacity: 0.7 }}>
                <CheckCircle size={16} color="#10b981" />
                <span style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>{step}</span>
              </div>
            ))}
          </div>
        )}

        {stage === 'result' && analysis && (
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
            {/* Profile Summary */}
            <div className="card" style={{ gridColumn: '1/-1' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                <div style={{ width: 56, height: 56, borderRadius: '50%', background: 'linear-gradient(135deg,#6366f1,#8b5cf6)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><User size={28} color="white" /></div>
                <div>
                  <h2 style={{ fontWeight: 700, color: '#f1f5f9' }}>{analysis.name}</h2>
                  <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>{analysis.seniority_level} Developer • {analysis.experience_years} years experience • Resume Score: <span style={{ color: '#34d399', fontWeight: 700 }}>{analysis.resume_score}/100</span></p>
                </div>
                <button className="btn-primary" style={{ marginLeft: 'auto' }} onClick={handleDownloadReport}>Download Report</button>
              </div>
            </div>

            {/* Extracted Skills */}
            <div className="card">
              <h3 style={{ fontWeight: 700, color: '#f1f5f9', marginBottom: '1.25rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Code2 size={18} color="#818cf8" /> Extracted Skills</h3>
              <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                {analysis.extracted_skills.map((s: string) => (
                  <span key={s} className="badge badge-primary" style={{ padding: '0.5rem 1rem' }}>{s}</span>
                ))}
              </div>
            </div>

            {/* Skill Gaps */}
            <div className="card">
              <h3 style={{ fontWeight: 700, color: '#f1f5f9', marginBottom: '1.25rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Target size={18} color="#f59e0b" /> Skill Gaps Identified</h3>
              {analysis.skill_gaps.map((g: string) => (
                <div key={g} style={{ padding: '0.75rem 1rem', borderRadius: '0.75rem', background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border)', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div>
                    <div style={{ fontWeight: 600, color: '#f1f5f9', fontSize: '0.9rem' }}>{g}</div>
                  </div>
                  <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <button className="btn-primary" style={{ padding: '0.3rem 0.75rem', fontSize: '0.78rem' }} onClick={() => handleLearnClick(g)}>Learn</button>
                    <button className="btn-outline" style={{ padding: '0.3rem 0.75rem', fontSize: '0.78rem', borderColor: 'rgba(99,102,241,0.3)' }} onClick={() => handleGeneratePath(g)}><TrendingUp size={12} /> Path</button>
                  </div>
                </div>
              ))}
              <button id="gen-path-btn" className="btn-outline" style={{ width: '100%', justifyContent: 'center', marginTop: '0.5rem', opacity: loading ? 0.7 : 1 }} onClick={() => handleGeneratePath()} disabled={loading}>
                {loading ? 'Generating...' : <><TrendingUp size={14} /> Generate Learning Path</>}
              </button>
            </div>

            {/* Suggestions */}
            <div className="card" style={{ gridColumn: '1/-1', background: 'rgba(16,185,129,0.04)', borderColor: 'rgba(16,185,129,0.2)' }}>
              <h3 style={{ fontWeight: 700, color: '#34d399', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Briefcase size={16} /> Resume Enhancement Tips</h3>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
                {analysis.suggestions.map((tip: string) => (
                  <div key={tip} style={{ display: 'flex', alignItems: 'flex-start', gap: '0.5rem', padding: '0.75rem', background: 'rgba(16,185,129,0.05)', borderRadius: '0.75rem' }}>
                    <CheckCircle size={14} color="#10b981" style={{ marginTop: 2, flexShrink: 0 }} />
                    <span style={{ fontSize: '0.875rem', color: '#94a3b8', lineHeight: 1.5 }}>{tip}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
